### Wybrane zagadnienia algebry liniowej, faktoryzacja
#### Wsparcie algebry liniowej w Julii
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html

In [1]:
using(LinearAlgebra)

In [2]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [3]:
x2=[1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [4]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [8]:
#iloczyn skalarny
dot(x,y)

48

 Dlugosc wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [5]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Array{Float64,2}:
 0.929095  0.0113385  0.291053
 0.571869  0.31164    0.932801
 0.677006  0.0686137  0.061284

In [6]:
#losujemy wektor x
x=rand(3)

3-element Array{Float64,1}:
 0.2935374262793098 
 0.10166498210175323
 0.9979679739339695 

In [7]:
# wyliczamy b
b=A*x

3-element Array{Float64,1}:
 0.5643381238607428 
 1.1304530084045408 
 0.26686164905045817

Sposoby rozwiązania Ax=b

In [8]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.29353742627930984
 0.10166498210175368
 0.9979679739339695 

In [9]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Array{Float64,1}:
 0.2935374262793098 
 0.10166498210175373
 0.9979679739339695 

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.0/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


In [10]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.615512  1.0       0.0
 0.728672  0.198095  1.0
U factor:
3×3 Array{Float64,2}:
 0.929095  0.0113385   0.291053
 0.0       0.304661    0.753654
 0.0       0.0        -0.300093

In [11]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.615512  1.0       0.0
 0.728672  0.198095  1.0

In [12]:
#Macierz U
Af.U

3×3 Array{Float64,2}:
 0.929095  0.0113385   0.291053
 0.0       0.304661    0.753654
 0.0       0.0        -0.300093

In [13]:
# wektor permulatacji 
Af.p

3-element Array{Int64,1}:
 1
 2
 3

In [14]:
# to jest spełnione
Af.L*Af.U==A[Af.p,:]

true

In [15]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.615512  1.0       0.0
 0.728672  0.198095  1.0
U factor:
3×3 Array{Float64,2}:
 0.929095  0.0113385   0.291053
 0.0       0.304661    0.753654
 0.0       0.0        -0.300093

In [16]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.2935374262793098 
 0.10166498210175373
 0.9979679739339695 

In [17]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Array{Float64,1}:
  0.47234330812962844
  4.700889610947438  
 -1.1444820958891702 

#### Faktoryzacja QR


In [19]:
B=rand(3,6)

3×6 Array{Float64,2}:
 0.858545  0.203717  0.459011  0.563714  0.530125  0.255547
 0.202027  0.992979  0.941589  0.18258   0.975559  0.705539
 0.797562  0.10719   0.401937  0.534062  0.355566  0.34307 

In [20]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
3×3 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.721997   0.0808162  -0.68716  
 -0.169895  -0.983456    0.0628453
 -0.670713   0.162119    0.723783 
R factor:
3×6 Array{Float64,2}:
 -1.18913  -0.387679  -0.534473  -0.796222   -0.786974   -0.76096  
  0.0      -0.94271   -0.617596  -0.0474203  -0.858933   -0.823754 
  0.0       0.0        0.117046   0.0106568  -0.0456194   0.0346758
permutation:
6-element Array{Int64,1}:
 1
 2
 6
 4
 5
 3

Jednym z zastosowań faktoryzacji QR jest uzycie jej do metody najmniejszych kwadratów

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znajeźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują:

$$\lVert y-A*wsp\rVert=\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}$$



1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [21]:
A=zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [22]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [23]:
A[:,1]=x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [24]:
A[:,2]=x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [25]:
A[:,3]=ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

2. Dokonujemy faktoryzacji QR macierzy A 

In [28]:
 AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788 
   0.0    -2.34816  -1.43091 
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

Wiecej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

In [29]:
# ortogonalność
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           1.11022e-16  …   8.32667e-17   0.0        
  0.0           1.0           9.71445e-17     -5.55112e-17  -1.249e-16  
  1.11022e-16   9.71445e-17   1.0             -4.16334e-17   0.0        
 -9.71445e-17   3.46945e-17   2.60209e-17     -9.88792e-17  -2.08167e-17
  8.32667e-17  -5.55112e-17  -4.16334e-17      1.0           0.0        
  0.0          -1.249e-16     0.0          …   0.0           1.0        

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [30]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285727
  3.942857142857152 
 -2.8000000000000163

Cały ten algorytm jest ukryty pod operatorem "\\". 

In [31]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285726
  3.942857142857151 
 -2.8000000000000145

In [32]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
polyfit(x,y, 2)

Poly(-2.8000000000000145 + 3.942857142857151*x - 0.5714285714285726*x^2)

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/ef129b779d08f791eb607e390ca9d31d8c08ead1/src/Polynomials.jl#L689-L707">
polyfit</a> uzywa własnie tej metody


### Zadania

#### Zadanie 1 
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x
Nastepnie rozwiąz rownanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie fukcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2
Policz wspołczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

