### Wybrane zagadnienia algebry liniowej, faktoryzacja
#### Wsparcie algebry liniowej w Julii
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html

In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::Union{DenseArray{T,2}, ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where T in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/dense.jl:1141
[2] factorize(A::Adjoint) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/dense.jl:1216
[3] factorize(A::Transpose) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/dense.jl:1217
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/triangular.jl:2475
[5] factorize(A::Union{Hermitian{Complex{Float64},#s576}, Hermitian{Float64,#s576}, Symmetric{Float64,#s576}} where #s576<:SparseArrays.SparseMatrixCSC) in SparseArrays at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/linalg.jl:1126
[6] factorize(A::Union{Hermitian{T,S}, Symmetric{T,S}} where S) where T in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/symmetric.jl:451
[7] factorize(A::Tridiagonal) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/lu.jl:494
[8] factorize(D::Diagonal) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/diagonal.jl:121
[9] factorize(A::Bidiagonal) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/bidiag.jl:616
[10] factorize(S::SymTridiagonal) in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/ldlt.jl:99
[11] factorize(A::SparseArrays.SparseMatrixCSC) in SparseArrays at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/linalg.jl:1096

In [3]:
@which factorize

LinearAlgebra

In [4]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [5]:
y1=[1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [6]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [7]:
#iloczyn skalarny
dot(x1,y1)

11

 Długosc wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [8]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Array{Float64,2}:
 0.829924  0.143978  0.497349
 0.57034   0.709877  0.131998
 0.168779  0.800209  0.578289

In [9]:
#losujemy wektor x
x=rand(3)

3-element Array{Float64,1}:
 0.38896654927691143
 0.6742730404007657 
 0.30383399681734446

In [10]:
# wyliczamy b
b=A*x

3-element Array{Float64,1}:
 0.5710044627687253
 0.7405998916982014
 0.7809131737727959

Sposoby rozwiązania Ax=b

In [11]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.3889665492769112
 0.6742730404007655
 0.3038339968173448

In [12]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Array{Float64,1}:
 0.38896654927691143
 0.6742730404007655 
 0.3038339968173447 

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.0/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


In [13]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.203367  1.0       0.0
 0.687219  0.792464  1.0
U factor:
3×3 Array{Float64,2}:
 0.829924  0.143978   0.497349
 0.0       0.770929   0.477145
 0.0       0.0       -0.587909

In [14]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.203367  1.0       0.0
 0.687219  0.792464  1.0

In [15]:
#Macierz U
Af.U

3×3 Array{Float64,2}:
 0.829924  0.143978   0.497349
 0.0       0.770929   0.477145
 0.0       0.0       -0.587909

In [16]:
# wektor permulatacji 
Af.p

3-element Array{Int64,1}:
 1
 3
 2

In [17]:
# to jest spełnione
Af.L*Af.U==A[Af.p,:]

false

In [18]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.203367  1.0       0.0
 0.687219  0.792464  1.0
U factor:
3×3 Array{Float64,2}:
 0.829924  0.143978   0.497349
 0.0       0.770929   0.477145
 0.0       0.0       -0.587909

In [19]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.38896654927691143
 0.6742730404007655 
 0.3038339968173447 

In [20]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Array{Float64,1}:
  0.3974673609489566 
 -0.30741411284036185
  0.8538470256589303 

#### Faktoryzacja QR


In [21]:
B=rand(10,5)

10×5 Array{Float64,2}:
 0.810107   0.010942  0.501333  0.4013     0.0390203 
 0.463484   0.750867  0.736212  0.984136   0.930265  
 0.60959    0.909777  0.936573  0.424918   0.463269  
 0.712242   0.199685  0.954528  0.586881   0.406423  
 0.68889    0.261117  0.714703  0.515855   0.468567  
 0.655471   0.190768  0.732162  0.136315   0.505406  
 0.671895   0.336872  0.179816  0.523185   0.231737  
 0.713833   0.39891   0.20669   0.302705   0.00383002
 0.257239   0.384435  0.677613  0.416978   0.192084  
 0.0233118  0.192837  0.972527  0.0162584  0.204231  

In [22]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.221809    0.403879    0.398841  …  -0.162815   -0.313643   -0.599072 
 -0.325728   -0.0270337  -0.472986      0.249059   -0.229423   -0.241147 
 -0.414376   -0.0173385  -0.542335     -0.45923    -0.180444   -0.0270339
 -0.422319    0.0600125   0.342014     -0.0951209  -0.193573    0.429031 
 -0.316212    0.177813    0.160264     -0.0042287   0.382987    0.282521 
 -0.323936    0.139246    0.243918  …   0.0707476   0.222841   -0.234137 
 -0.0795572   0.470511   -0.163056     -0.28991     0.0439682   0.391792 
 -0.0914477   0.49089    -0.215737      0.718479   -0.0138031   0.0979772
 -0.299802   -0.169507   -0.108944     -0.0164285   0.717812   -0.272586 
 -0.430283   -0.538661    0.189552      0.293201   -0.255434    0.161622 
R factor:
5×5 Array{Float64,2}:
 -2.2602  -1.5201   -1.1142    -1.24209   -1.15141 
  0.0      1.17098   0.238608   0.589353   0.129007
  0.0      0.0      -

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znajeźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [23]:
A=zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [24]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [25]:
A[:,1]=x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [26]:
A[:,2]=x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [27]:
A[:,3]=ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [28]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

2. Dokonujemy faktoryzacji QR macierzy A 

In [29]:
 AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788 
   0.0    -2.34816  -1.43091 
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

In [30]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           1.11022e-16  …   8.32667e-17   0.0        
  0.0           1.0           9.71445e-17     -5.55112e-17  -1.249e-16  
  1.11022e-16   9.71445e-17   1.0             -4.16334e-17   0.0        
 -9.71445e-17   3.46945e-17   2.60209e-17     -9.88792e-17  -2.08167e-17
  8.32667e-17  -5.55112e-17  -4.16334e-17      1.0           0.0        
  0.0          -1.249e-16     0.0          …   0.0           1.0        

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [31]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285727
  3.942857142857152 
 -2.8000000000000163

Wiecej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [32]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285726
  3.942857142857151 
 -2.8000000000000145

In [33]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
polyfit(x,y, 2)

Poly(-2.8000000000000145 + 3.942857142857151*x - 0.5714285714285726*x^2)

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/ef129b779d08f791eb607e390ca9d31d8c08ead1/src/Polynomials.jl#L689-L707">
polyfit</a> używa własnie tej metody


### Zadania

#### Zadanie 1 
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x
Nastepnie rozwiąz rownanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie fukcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2
Policz wspołczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy(http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych(https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254


