### Wybrane zagadnienia algebry liniowej, faktoryzacja
#### Wsparcie algebry liniowej w Julii
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html

In [2]:
using(LinearAlgebra)

In [2]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [3]:
y1=[1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [4]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [5]:
#iloczyn skalarny
dot(x1,y1)

11

 Długosc wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [6]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Array{Float64,2}:
 0.0766579  0.0660499  0.153052 
 0.0150662  0.855318   0.740491 
 0.492154   0.156875   0.0469833

In [7]:
#losujemy wektor x
x=rand(3)

3-element Array{Float64,1}:
 0.8567664643938591 
 0.5128338539122037 
 0.32684235680683194

In [8]:
# wyliczamy b
b=A*x

3-element Array{Float64,1}:
 0.14957445707906936
 0.6935678631125135 
 0.5174686524871231 

Sposoby rozwiązania Ax=b

In [9]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.8567664643938592 
 0.5128338539122036 
 0.32684235680683227

In [10]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Array{Float64,1}:
 0.8567664643938592 
 0.5128338539122036 
 0.32684235680683216

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.0/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


In [11]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0        0.0
 0.0306128  1.0        0.0
 0.15576    0.0489292  1.0
U factor:
3×3 Array{Float64,2}:
 0.492154  0.156875  0.0469833
 0.0       0.850515  0.739052 
 0.0       0.0       0.109573 

In [12]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0        0.0        0.0
 0.0306128  1.0        0.0
 0.15576    0.0489292  1.0

In [13]:
#Macierz U
Af.U

3×3 Array{Float64,2}:
 0.492154  0.156875  0.0469833
 0.0       0.850515  0.739052 
 0.0       0.0       0.109573 

In [14]:
# wektor permulatacji 
Af.p

3-element Array{Int64,1}:
 3
 2
 1

In [15]:
# to jest spełnione
Af.L*Af.U==A[Af.p,:]

true

In [16]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0        0.0
 0.0306128  1.0        0.0
 0.15576    0.0489292  1.0
U factor:
3×3 Array{Float64,2}:
 0.492154  0.156875  0.0469833
 0.0       0.850515  0.739052 
 0.0       0.0       0.109573 

In [17]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.8567664643938592 
 0.5128338539122036 
 0.32684235680683216

In [18]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Array{Float64,1}:
  1.7179026889471467
 -3.0513930192597334
  4.560807151983948 

#### Faktoryzacja QR


In [1]:
B=rand(10,5)

10×5 Array{Float64,2}:
 0.0198947  0.954631   0.826587  0.963496  0.905644 
 0.757499   0.227189   0.855952  0.847453  0.764729 
 0.395098   0.271207   0.444343  0.929014  0.564965 
 0.198918   0.978924   0.20125   0.285582  0.953734 
 0.634862   0.7246     0.235526  0.309163  0.0154049
 0.255717   0.359512   0.99451   0.637464  0.822492 
 0.136852   0.326067   0.381503  0.780533  0.480194 
 0.365437   0.0226417  0.182084  0.449994  0.213073 
 0.222296   0.1038     0.519317  0.782098  0.251162 
 0.987462   0.962615   0.272671  0.193038  0.665212 

In [3]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.451508    0.270113     0.548554   …   0.0663182  -0.301888    0.329679 
 -0.397129   -0.177632    -0.449774      -0.133716   -0.176661    0.0381285
 -0.43535    -0.179709    -0.0727151     -0.407545   -0.198124   -0.414314 
 -0.133828    0.551883     0.243499       0.119804    0.327118   -0.369234 
 -0.144879    0.37024     -0.260341       0.0745919  -0.0699235  -0.42749  
 -0.298725   -0.00574604   0.0303438  …   0.121143    0.0619285  -0.272668 
 -0.365769   -0.0844093    0.160734      -0.0416046  -0.132472    0.274072 
 -0.210874   -0.160756    -0.241122       0.867421   -0.0980752   0.0120323
 -0.366503   -0.235704    -0.0039691     -0.0467324   0.832397    0.174797 
 -0.0904605   0.577044    -0.528699      -0.143885    0.0511628   0.46793  
R factor:
5×5 Array{Float64,2}:
 -2.13395  -1.23186  -0.974717  -1.70693    -1.65766  
  0.0       1.47507   0.590292   0.784456    0.157

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znajeźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$



Jak użyć do tej mimalizacji faktoryzacji QR:

1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [21]:
A=zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [22]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [23]:
A[:,1]=x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [24]:
A[:,2]=x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [25]:
A[:,3]=ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

2. Dokonujemy faktoryzacji QR macierzy A 

In [27]:
 AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788 
   0.0    -2.34816  -1.43091 
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

In [28]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           1.11022e-16  …   8.32667e-17   0.0        
  0.0           1.0           9.71445e-17     -5.55112e-17  -1.249e-16  
  1.11022e-16   9.71445e-17   1.0             -4.16334e-17   0.0        
 -9.71445e-17   3.46945e-17   2.60209e-17     -9.88792e-17  -2.08167e-17
  8.32667e-17  -5.55112e-17  -4.16334e-17      1.0           0.0        
  0.0          -1.249e-16     0.0          …   0.0           1.0        

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [29]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285727
  3.942857142857152 
 -2.8000000000000163

Wiecej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [30]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285726
  3.942857142857151 
 -2.8000000000000145

In [31]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
polyfit(x,y, 2)

Poly(-2.8000000000000145 + 3.942857142857151*x - 0.5714285714285726*x^2)

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/ef129b779d08f791eb607e390ca9d31d8c08ead1/src/Polynomials.jl#L689-L707">
polyfit</a> używa własnie tej metody


### Zadania

#### Zadanie 1 
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x
Nastepnie rozwiąz rownanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie fukcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2
Policz wspołczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

